### PR TITLE
Added Make File

### LINKED ISSUE #65: Add Makefile
### Description

Transfer the build scripts from `package.json` to Makefile -- it would give more control over what we can do, moving further on

### Domain

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Rishabh-malhotraa/Vita/blob/main/CODE_OF_CONDUCT.md) of this project.

### PR DESCRIPTION
**Pull request by Harshil-Jani**
Closes #65 
This PR contains the MakeFile which makes the tasks of Package.Json easier to execute.

### CODE REVIEW

**Comment by Rishabh-malhotraa** [comment]
Thanks for the PR. can you remove the package-lock.json changes, i think the reason you got a different file is because you are using lockVersion:1 but we have moved to lockVersion:2

**Comment by Sahaj-Srivastava24** [comment]
Thanks, @Harshil-Jani. I'll be merging your PR.

**Comment by Rishabh-malhotraa** [comment]
@Sahaj-Srivastava24 we should not be having 27000 deletions when we are trying to add a `makefile` it can cause a big problem, in future.
It is caused because I might have git push --force on a commit and the contributor did not git pull causing a lot od differences, I'll fix this one, but be more careful in the future

**Comment by Rishabh-malhotraa** [comment]
@all-contributors please add @Harshil-Jani for infra

**Pull request merged**
