### PR TITLE
fts on mentor implemented

### PR DESCRIPTION
**Pull request by Gurdeep475**
Full-Text Search on Mentor Model is implemented using MongoDB text search Index.
closes: #14

### CODE REVIEW

**Comment by Rishabh-malhotraa** [comment]
Thanks for the pr, rather than creating a new controller can we add this in getMentorsController itself?

**Comment by Gurdeep475** [comment]
> Thanks for the pr, rather than creating a new controller can we add this in getMentorsController itself?

Yes, it can be done, need an if check for query parameter to do fts

**Comment by Rishabh-malhotraa** [comment]
The reason I want it in the getMentor controller is because I want all these parameters to be chained together, just like how search  on leetcode works


So on the front-end we would have a UI of something similar to the following
image

**Comment by Gurdeep475** [comment]
The said changes have been made, now text-search is chained with Expertise and topics filters inside getMentorsController.
image

**Pull request merged**
