### PR TITLE
Add email service

### LINKED ISSUE #10: Add SMTP Sever
Incorporate SMTP server to send emails to mentor-mentee when their booking is confirmed and also reminder email 30 minutes before the meeting 

Also in the confirmed meeting email send an ics file
https://www.npmjs.com/package/ics

https://nodemailer.com/about/

https://www.youtube.com/watch?v=nF9g1825mwk

### PR DESCRIPTION
**Pull request by hazemessam**
closes #10

### CODE REVIEW

**Review by Lalit3716 — APPROVED** [review]
Looks good to me!

**Comment by hazemessam** [comment]
@Rishabh-malhotraa Please, can you check that

**Comment by Rishabh-malhotraa** [comment]
Thank you, will try to get it merged this week, or next week!

**Comment by Rishabh-malhotraa** [comment]
LGTM, thank you @hazemessam

**Pull request merged**
