### PR TITLE
Added: Footer Component

### PR DESCRIPTION
**Pull request by Lalit3716**
Closes Issue #50

Screenshot:-
Screenshot 2022-03-06 195556

### CODE REVIEW

**Comment by Rishabh-malhotraa** [comment]
This looks great! thanks for the PR @Lalit3716  @SidharthMishra-07 
I'll merge it soon

**Comment by Lalit3716** [comment]
Glad you liked it ❤️

> This looks great! thanks for the PR @Lalit3716 @SidharthMishra-07 I'll merge it soon

**Comment by Rishabh-malhotraa** [comment]
can we make it dark theme? Like this

image

I got the dark theme by using the extension [dark reader](https://chrome.google.com/webstore/detail/dark-reader/eimadpbcbfnmbkopoojfekhnkhdbieeh?hl=en)

**Comment by Lalit3716** [comment]
Sure I will make it dark themed.

**Comment by Lalit3716** [comment]
Are we storing user preference of dark theme and light theme in localstorage or somewhere ?

**Comment by Rishabh-malhotraa** [comment]
> Are we storing user preference of dark theme and light theme in localstorage or somewhere ?

Right now it's only dark theme 🥲

**Comment by Sahaj-Srivastava24** [comment]
Hey @Lalit3716. 
I went through your pr and most of the things look good except for a bit of changes I'll be pointing out here,

- Can you push the div with copyright tag to the very end of the page on mobile screens..? It looks a bit absurd to see content even after the copyright tag which usually denotes the end of the page. 

- We'll be having our socials limited to Github , Gmail and LinkedIn, so drop the other two icons. 

- You've imported the logo with absolute addressing that could bug out later as we won't be storing these assets on the client side, rather use a cloud service to serve them. For now, just use relative addressing for imports.

**Comment by Lalit3716** [comment]
Hey @Sahaj-Srivastava24 thanks for reviewing the PR. I tried solving first two points you mentioned so do have a look on new footer and let me know any further improvements!.

> * You've imported the logo with absolute addressing that could bug out later as we won't be storing these assets on the client side, rather use a cloud service to serve them. For now, just use relative addressing for imports.

As for the third point could you please elaborate on this as I don't quite understand it like why should we use relative path instead of absolute one? Thanks!

**Comment by Rishabh-malhotraa** [comment]
> Hey @Sahaj-Srivastava24 thanks for reviewing the PR. I tried solving first two points you mentioned so do have a look on new footer and let me know any further improvements!.
> 
> > * You've imported the logo with absolute addressing that could bug out later as we won't be storing these assets on the client side, rather use a cloud service to serve them. For now, just use relative addressing for imports.
> 
> As for the third point could you please elaborate on this as I don't quite understand it like why should we use relative path instead of absolute one? Thanks!

What he means is we would be using AWS s3 in production to serve the, you can skip that for now.

**Comment by Lalit3716** [comment]
> > Hey @Sahaj-Srivastava24 thanks for reviewing the PR. I tried solving first two points you mentioned so do have a look on new footer and let me know any further improvements!.
> > > * You've imported the logo with absolute addressing that could bug out later as we won't be storing these assets on the client side, rather use a cloud service to serve them. For now, just use relative addressing for imports.
> > 
> > 
> > As for the third point could you please elaborate on this as I don't quite understand it like why should we use relative path instead of absolute one? Thanks!
> 
> What he means is we would be using AWS s3 in production to serve the, you can skip that for now.

Oh okk!

**Comment by Rishabh-malhotraa** [comment]
LGTM 🎉

**Pull request merged**
